apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ack-jenkins-demo-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ack-jenkins-demo-pipeline
  template:
    metadata:
      labels:
        app: ack-jenkins-demo-pipeline
    spec:
      containers:
      - name: ack-jenkins-demo-pipeline
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ack-jenkins-demo-pipeline
spec:
  ports:
  - port: 80
    targetPort: 80
    name: ack-jenkins-demo-pipeline
  selector:
    app: ack-jenkins-demo-pipeline
  type: LoadBalancer
